name: image-cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up images
        uses: snok/container-retention-policy@v2
        with:
          image-names: dependabot-gitlab, dependabot-gitlab-*
          filter-tags: dev-*
          org-name: dependabot-gitlab
          account-type: org
          cut-off: 1 day ago UTC
          keep-at-least: 5
          filter-include-untagged: true
          token: ${{ secrets.CONTAINER_DELETE_TOKEN }}
